language: node_js
node_js:
- '6.1'
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: lzE+qmkTXBA0Hb46s4Cq1gkGiVqjr1nbUJ/2X0vuLOAOTPhTP7MbzRQKRo8HBg/Mg/IoI8VSvgV/AN/Wm6TFlpV23Xhh3PBIuKaeMAejHiHBEcUUkBWC04uU+J9SsXaucaFbZ4vQvQXHDUT9zOqkXW+1MSb52KTTE1PYn5sjLEOjLAZTN1rwm5Fg0XTHVKC+5Y+SLWZwCYvO6Pc2cSPPjdjAi4KE1b+r3XLQ60tN6bda72XdryWQYQadBgYBHY/uOCOXtchFN7yWRslXxdUJoEeBQq4Uob+A1CR3suml8q/1FJMphdkAcWT8sNEvLYhFSRlt2NZfcag7Brl06Mu5wsfqYaL1NtNq8//YorRmEuTb8bRzMVB1yZJ2Gbfk5FDa4bpPH/k/2fX/QwOQNEtEKiNqGWCbwYAbFmWo1rUFmFiFRVjvf7hgGf2E0i8Lydj2iP1pjfLKcQ7yhDdQUNnUN+4GIZzSmO2hpk8R2yJOUkdKGhHSnvVMyowSnB4iEA2QvaqjftAsJQGWNWlSlQA5vz5CAezHSGXl9hvu/GgtuoOVGjCm31lWbf7dAYTHeYLrxj3Z5KJ5KTxWZ91XkXh7oqn9XTTM4vOXtsNlM5f+gS5j7QIB8y4viGYqgf1IYM5K6lONNhzWG71VgkJqXzox7O5dcPtEZ/LIBXFQGuwmNws=
